// AUTO-GENERATED FILE. Do not edit manually.
// Generated by scripts/import-keywords.ts
export type KeywordEntry = { keyword: string; intent: string; cluster: string; target_url: string; notes?: string };
export const keywordEntries: KeywordEntry[] = [
  {
    "keyword": "szkoła jazdy bydgoszcz",
    "intent": "lokalna",
    "cluster": "home",
    "target_url": "/",
    "notes": "map_pack;local;reviews"
  },
  {
    "keyword": "kurs prawa jazdy bydgoszcz",
    "intent": "transakcyjna",
    "cluster": "kursy",
    "target_url": "/kursy",
    "notes": "fs;organic"
  },
  {
    "keyword": "cennik prawa jazdy bydgoszcz",
    "intent": "komercyjna",
    "cluster": "cennik",
    "target_url": "/cennik",
    "notes": "fs;organic"
  },
  {
    "keyword": "jazdy doszkalające bydgoszcz",
    "intent": "komercyjna",
    "cluster": "kursy",
    "target_url": "/kursy",
    "notes": "organic;local"
  },
  {
    "keyword": "jak zapisać się na kurs prawa jazdy",
    "intent": "informacyjna",
    "cluster": "faq",
    "target_url": "/pytania",
    "notes": "paa;fs"
  }
] as const;
export const availableRoutes: string[] = [
  "/",
  "/cennik",
  "/galeria",
  "/kontakt",
  "/kursy",
  "/o-nas",
  "/poradnik",
  "/poradnik/[slug]",
  "/pytania",
  "/rezerwacja",
  "/rezerwacja/dziekujemy",
  "/seo/audyt",
  "/seo/keywords"
] as const;

// Compatibility exports for dev panel (/seo/keywords)
export type KeywordRecord = {
  keyword: string;
  intent: string;
  cluster: string;
  targetUrl: string;
  notes?: string;
  volume?: number;
  kd?: number;
  cpc_pln?: number;
  trend_12m?: string;
  serpTypes?: string;
  priority?: 'HIGH' | 'MEDIUM' | 'LOW';
};
export const keywords: KeywordRecord[] = keywordEntries.map((k) => ({
  keyword: k.keyword,
  intent: k.intent,
  cluster: k.cluster,
  targetUrl: k.target_url,
  notes: k.notes,
  serpTypes: k.notes,
  priority: 'MEDIUM',
}));
export function getAllClusters(): string[] {
  return Array.from(new Set(keywords.map((k) => k.cluster))).sort();
}
export function getAllIntents(): string[] {
  return Array.from(new Set(keywords.map((k) => k.intent))).sort();
}
